config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/get_random_service_tag', to: 'pages#get_random_service_tag', as: 'get_random_service_tag'
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :products, through: :line_items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    #belongs_to :category

    has_many :line_items
    has_many :carts, through: :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #http_basic_authenticate_with name: 'yugesh', password: '123456' if Rails.env.development?
    include BasicAuth
end

app/controllers/concerns/basic_auth.rb
module BasicAuth
    extend ActiveSupport::Concern
    included do
        before_action :staging_authentication
    end

    def staging_authentication
        return true unless Rails.env.staging?

        authenticate_or_request_with_http_basic do |name, password|
            name == 'yugesh' && password == '123456'
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def get_random_service_tag
    @service_tag = "#{rand(10..99)}-#{[*('A'..'Z')].sample(8).join}-#{rand(2222..9999)}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Egadgetstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 align="center"> E-Gadget Store </h1>
    <hr />
    <%= render "shared/nav_links" %>
    <hr />
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/get_random_service_tag.js.erb
document.getElementById('result').innerHTML = "<%= j @service_tag%>"

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Get Random Service Tag", get_random_service_tag_path, remote: true %>
<div id="result"></div>

app/views/shared/_nav_links.html.erb
<ol>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
</ol>